Algoritmo "Quantos anos"

Var
// Seção de Declarações das variáveis 
  ano_atual, ano_nasc, idade: inteiro
  

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
       Escreval ("Em que ano nós estamos? ")
       Leia(ano_atual)
       Escreval ("Em que ano eu nasci? ")
       Leia (ano_nasc)
       idade<- ano_atual - ano_nasc
       Escreva("Minha idade é: ", idade)

Fimalgoritmo