Algoritmo "semnome"
      //Operadores Relacionais
Var
// Seção de Declarações das variáveis
A, B, C: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
     A <- 2
     B <- 3
     C <- 5
     
     Escreval (A>B)
     Escreval (A=B)
     Escreval (A<>B)
     Escreval (A<B)
     Escreval (A>2)
     Escreval (A>=B)
     Escreval (C=A+B)
     Escreval (C>=B^A)
     Escreval (C<=B^A)
     Escreval (B<=C%2)
     Escreval (1=C%2)

Fimalgoritmo